import express from "express";
import authRouter from "./routes/auth-routes.js";
import cookieParser from "cookie-parser";
import imageRouter from "./routes/upload-routes.js";
import cors from "cors";
const app = express();
app.use(express.json());
app.use(cookieParser());
app.use(cors());
app.use("/api/auth", authRouter);
app.use("/api/image", imageRouter);
export default app;
